import{proof as p}from'../content-depth/profile.mjs'
const q=(a,s,e,n,x)=>p(a,'sql',s,e,n,x),N=(a,b,c)=>[[a,'记录稳态基线',b,c],[`${a} P99`,'同负载可复现',`超过基线 2 倍`,c],['结果核对','差异为 0','任意非零','停止切换并修复']],X=(a,b,c)=>[a,b,c]
export const clickhouseProofs={
 'clickhouse/mergetree':q([['system.parts','Part 数、行数和级别'],['src/Storages/MergeTree','写 Part 与后台 merge']],`SELECT partition,count(),sum(rows) FROM system.parts WHERE active GROUP BY partition;`,'用每行/千行/万行批次持续写 30 分钟，对比 Part 生成与合并净速率。',N('active parts','持续增长','合并跟不上'),X('客户端攒批或 async_insert','降低分区粒度','为 merge 保留 CPU/I/O')),
 'clickhouse/partition-order-primary-key':q([['system.parts','分区与 Part 物理分布'],['EXPLAIN indexes=1','分区/主键裁剪']],`EXPLAIN indexes=1 SELECT count() FROM events WHERE tenant_id=7 AND event_time>=now()-INTERVAL 1 DAY;`,'以三种 ORDER BY 回放 Top 查询，比较读取 granule 和压缩比。',N('read_rows/result_rows','>100','排序键失配'),X('低基数时间分区','ORDER BY 前缀匹配查询','禁止把主键当唯一约束')),
 'clickhouse/query-optimization':q([['system.query_log','read_rows、memory_usage、ProfileEvents'],['EXPLAIN PIPELINE','并行执行管线']],`SELECT query_duration_ms,read_rows,memory_usage FROM system.query_log WHERE type='QueryFinish' ORDER BY event_time DESC LIMIT 20;`,'固定数据快照对比 PREWHERE、投影和预聚合，混合并发下验证。',N('read_rows/result_rows','>1000','读放大'),X('先减少扫描列和行','限制高基数聚合','按并发而非单查询调线程')),
 'clickhouse/data-skipping-index':q([['EXPLAIN indexes=1','跳数索引命中与 granule'],['system.data_skipping_indices','索引定义']],`ALTER TABLE events ADD INDEX idx_status status TYPE set(100) GRANULARITY 4;`,'构造有序/随机分布并比较 minmax、set、Bloom 的跳过率。',N('granules dropped','低于 10%','索引无收益'),X('谓词匹配索引类型','无收益索引删除','优先优化 ORDER BY')),
 'clickhouse/write-optimization':q([['system.asynchronous_inserts','异步写缓冲'],['system.part_log','NewPart/MergeParts 事件']],`SET async_insert=1, wait_for_async_insert=1;`,'按 100/1万/10万行批次写入，记录 insert P99、内存与 Part 数。',N('parts/min','超过 merge/min','写入失稳'),X('批量写入','设置 wait_for_async_insert','重试使用去重 token')),
 'clickhouse/replacing-mergetree':q([['ReplacingSortedAlgorithm','版本替换逻辑'],['system.parts','旧新版本所在 Part']],`SELECT id,argMaxState(value,version) FROM state GROUP BY id;`,'同键写 3 个乱序版本，比较普通查询、FINAL 与 argMax 的正确性和成本。',N('同键版本数','持续>2','merge 延迟'),X('显式 version 列','高频读用 argMax/快照','限制全表 FINAL')),
 'clickhouse/distributed-table':q([['system.clusters','分片副本拓扑'],['system.distribution_queue','异步分布写队列']],`SELECT shard_num,replica_num,host_name FROM system.clusters WHERE cluster='prod';`,'制造倾斜 Key 与节点扩容，比较各分片行数、QPS 和协调内存。',N('max/avg shard rows','>1.5','分片倾斜'),X('稳定 sharding_key','协调聚合前下推','扩容用槽迁移/核对')),
 'clickhouse/advantages-limitations':q([['system.query_log','分析型扫描证据'],['system.mutations','更新删除队列']],`SELECT count(),sum(read_rows),sum(memory_usage) FROM system.query_log WHERE event_date=today();`,'同一事务点查、范围聚合和批量写在 MySQL/CH 上对比，明确访问模式。',N('mutation backlog','持续增长','模型不适配'),X('事务事实留 OLTP','分析通过 CDC 入 CH','避免高频行更新')),
 'clickhouse/concurrency-limitations':q([['system.processes','运行查询资源'],['system.query_log','峰值内存与排队']],`SELECT user,count(),sum(memory_usage) FROM system.processes GROUP BY user;`,'逐级增加并发直到 P99 非线性上升，记录拐点作为配额。',N('running queries','超过拐点','资源饱和'),X('按 workload 配额','客户端超时同步取消','预聚合重复查询')),
 'clickhouse/production-optimization':q([['system.metric_log','CPU/I/O/内存时间线'],['system.part_log/query_log','写合并与查询关联']],`SELECT event_type,count(),sum(duration_ms) FROM system.part_log GROUP BY event_type;`,'混合写入、查询、merge 和副本恢复压测，验证系统稳态而非单项峰值。',N('merge debt','持续增长','后台失稳'),X('建立混合负载基线','灰度一次改一个变量','磁盘水位前置扩容'))
}
